services:
  db:
    image: postgres:16
    container_name: bridge_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bridge_db
    ports:
      - "5432:5432"
